---
# HANDLERS:
- name: config web server
  hosts: webservers
  become: yes
  tasks:
    - name: install nginx
      apt:
        name: nginx
        state: present
      notify:
        - start nginx
        - enable nginx
    - name: config nginx
      template:
        src: nginx.conf.j2
        dest: /etc/nginx/nginx.conf
        backup: yes
      notify: restart nginx
    - name: copy config site
      template:
        src: default.j2
        dest: /etc/nginx/stes-available/default
      notify: reload nginx
    - name: check config nginx
      command: nginx -t
      register: nginx_syntax
      changed_when: false
      notify: restart nginx
  handlers:
    - name: start nginx
      service:
        name: nginx
        state: started
    - name: restarted nginx
      service:
        name: nginx
        state: restarted
    - name: enable nginx
      service:
        name: nginx
        enabled: yes
    - name: reload nginx
      service:
        name: nginx
        state: reloaded