---
# tasks file for roles
- name: Crear inventario dinámico
  add_host:
    name: "{{ item.name }}"
    groups: "{{ item.group }}"
    ansible_host: "{{ item.ip }}"
    ansible_user: "{{ ssh_user }}"
    #ansible_ssh_private_key_file: "{{ ssh_key }}"
  loop:
    - { name: "db-server", group: "database", ip: "172.19.0.5" }
    - { name: "api-server-1", group: "backend", ip: "172.19.0.5" }
    - { name: "web-server-1", group: "frontend", ip: "172.19.0.5" }
